AUDIO_ENABLE = yes
CAPS_WORD_ENABLE = yes
LEADER_ENABLE = yes
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
DYNAMIC_MACRO_DELAY = 5
DYNAMIC_MACRO_NO_NESTING = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes

# Include custom source files
SRC += zsa.c
